apiVersion: v1
kind: Service
metadata:
  name: task3-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: task3
  name: task3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task3
    spec:
      containers:
      - image: task2
        name: task2
        resources: {}
        ports:
          - containerPort: 80
status: {}
