apiVersion: v1
kind: Service
metadata:
  name: task3-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: task2
  name: task2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task2
    spec:
      containers:
      - image: task2-kube
        name: task2-container
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
          - containerPort: 80
status: {}
